class MonthObj {
    constructor(month, verseArray) {
        this._month = month;
        this._verseArray = verseArray;
    }
    get month(){
        return this._month;
    }
    get verseArray(){
        return this._verseArray;
    }
};

// instantiation of January
const january = new MonthObj('January', [
    ['In the beginning God created the heaven and the earth. ~<em>Genesis 1:1</em>~'],
['For I know the plans I have for you, declares the Lord, plans for welfare and not for evil, to give you a future and a hope. ~<em>Jeremiah 29:11</em>~'],
['The Lord is my shepherd; I shall not want. ~<em>Psalm 23:1</em>~'],
['I can do all things through Christ who strengthens me. ~<em>Philippians 4:13</em>~'],
['And we know that in all things God works for the good of those who love him, who have been called according to his purpose. ~<em>Romans 8:28</em>~'],
['For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life. ~<em>John 3:16</em>~'],
['But the fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness, gentleness and self-control. Against such things there is no law. ~<em>Galatians 5:22-23</em>~'],
['Trust in the Lord with all your heart and lean not on your own understanding; in all your ways submit to him, and he will make your paths straight. ~<em>Proverbs 3:5-6</em>~'],
['The Lord bless you and keep you; the Lord make his face shine on you and be gracious to you; the Lord turn his face toward you and give you peace. ~<em>Numbers 6:24-26</em>~'],
['But those who hope in the Lord will renew their strength. They will soar on wings like eagles; they will run and not grow weary, they will walk and not be faint. ~<em>Isaiah 40:31</em>~'],
['Jesus Christ is the same yesterday and today and forever. ~<em>Hebrews 13:8</em>~'],
['The Lord is my light and my salvation—whom shall I fear? The Lord is the stronghold of my life—of whom shall I be afraid? ~<em>Psalm 27:1</em>~'],
['Rejoice in the Lord always. I will say it again: Rejoice! ~<em>Philippians 4:4</em>~'],
['For we live by faith, not by sight. ~<em>2 Corinthians 5:7</em>~'],
['Therefore, if anyone is in Christ, the new creation has come: The old has gone, the new is here! ~<em>2 Corinthians 5:17</em>~'],
['Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go. ~<em>Joshua 1:9</em>~'],
['And my God will meet all your needs according to the riches of his glory in Christ Jesus. ~<em>Philippians 4:19</em>~'],
['Now faith is confidence in what we hope for and assurance about what we do not see. ~<em>Hebrews 11:1</em>~'],
['The Lord is near to all who call on him, to all who call on him in truth. ~<em>Psalm 145:18</em>~'],
['So do not fear, for I am with you; do not be dismayed, for I am your God. I will strengthen you and help you; I will uphold you with my righteous right hand. ~<em>Isaiah 41:10</em>~'],
['Come to me, all you who are weary and burdened, and I will give you rest. ~<em>Matthew 11:28</em>~'],
['For where two or three gather in my name, there am I with them. ~<em>Matthew 18:20</em>~'],
['Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God. ~<em>Philippians 4:6</em>~'],
['And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus. ~<em>Philippians 4:7</em>~'],
['In the same way, let your light shine before others, that they may see your good deeds and glorify your Father in heaven. ~<em>Matthew 5:16</em>~'],
['But seek first his kingdom and his righteousness, and all these things will be given to you as well. ~<em>Matthew 6:33</em>~'],
['For the wages of sin is death, but the gift of God is eternal life in Christ Jesus our Lord. ~<em>Romans 6:23</em>~'],
['For I am convinced that neither death nor life, neither angels nor demons, neither the present nor the future, nor any powers, neither height nor depth, nor anything else in all creation, will be able to separate us from the love of God that is in Christ Jesus our Lord. ~<em>Romans 8:38-39</em>~'],
['But God demonstrates his own love for us in this: While we were still sinners, Christ died for us. ~<em>Romans 5:8</em>~'],
['The name of the Lord is a fortified tower; the righteous run to it and are safe. ~<em>Proverbs 18:10</em>~'],
['Cast all your anxiety on him because he cares for you. ~<em>1 Peter 5:7</em>~']        
]);

const february = new MonthObj('February', [
    ['The steadfast love of the Lord never ceases; his mercies never come to an end; they are new every morning; great is your faithfulness. ~<em>Lamentations 3:22-23</em>~'],
['We love because he first loved us. ~<em>1 John 4:19</em>~'],
['The Lord is good, a refuge in times of trouble. He cares for those who trust in him. ~<em>Nahum 1:7</em>~'],
['For it is by grace you have been saved, through faith—and this is not from yourselves, it is the gift of God. ~<em>Ephesians 2:8</em>~'],
['Finally, be strong in the Lord and in his mighty power. ~<em>Ephesians 6:10</em>~'],
['I have hidden your word in my heart that I might not sin against you. ~<em>Psalm 119:11</em>~'],
['But he was pierced for our transgressions, he was crushed for our iniquities; the punishment that brought us peace was on him, and by his wounds we are healed. ~<em>Isaiah 53:5</em>~'],
['Above all, love each other deeply, because love covers over a multitude of sins. ~<em>1 Peter 4:8</em>~'],
['This is the day the Lord has made; let us rejoice and be glad in it. ~<em>Psalm 118:24</em>~'],
['Your word is a lamp for my feet, a light on my path. ~<em>Psalm 119:105</em>~'],
['Do to others as you would have them do to you. ~<em>Luke 6:31</em>~'],
['And whatever you do, whether in word or deed, do it all in the name of the Lord Jesus, giving thanks to God the Father through him. ~<em>Colossians 3:17</em>~'],
['Therefore, if anyone is in Christ, the new creation has come: The old has gone, the new is here! ~<em>2 Corinthians 5:17</em>~'],
['For where your treasure is, there your heart will be also. ~<em>Matthew 6:21</em>~'],
['For we are God’s handiwork, created in Christ Jesus to do good works, which God prepared in advance for us to do. ~<em>Ephesians 2:10</em>~'],
['Be still, and know that I am God; I will be exalted among the nations, I will be exalted in the earth. ~<em>Psalm 46:10</em>~'],
['Therefore do not worry about tomorrow, for tomorrow will worry about itself. Each day has enough trouble of its own. ~<em>Matthew 6:34</em>~'],
['For we are more than conquerors through him who loved us. ~<em>Romans 8:37</em>~'],
['A new command I give you: Love one another. As I have loved you, so you must love one another. ~<em>John 13:34</em>~'],
['The Lord is gracious and compassionate, slow to anger and rich in love. ~<em>Psalm 145:8</em>~'],
['The earth is the Lord’s, and everything in it, the world, and all who live in it. ~<em>Psalm 24:1</em>~'],
['Therefore go and make disciples of all nations, baptizing them in the name of the Father and of the Son and of the Holy Spirit. ~<em>Matthew 28:19</em>~'],
['Blessed are the peacemakers, for they will be called children of God. ~<em>Matthew 5:9</em>~'],
['And without faith it is impossible to please God, because anyone who comes to him must believe that he exists and that he rewards those who earnestly seek him. ~<em>Hebrews 11:6</em>~'],
['Do not let your hearts be troubled. You believe in God; believe also in me. ~<em>John 14:1</em>~'],
['For I am the Lord your God who takes hold of your right hand and says to you, Do not fear; I will help you. ~<em>Isaiah 41:13</em>~'],
['I lift up my eyes to the mountains—where does my help come from? My help comes from the Lord, the Maker of heaven and earth. ~<em>Psalm 121:1-2</em>~'],
['But seek first his kingdom and his righteousness, and all these things will be given to you as well. ~<em>Matthew 6:33</em>~'],
['No weapon forged against you will prevail, and you will refute every tongue that accuses you. This is the heritage of the servants of the Lord, and this is their vindication from me, declares the Lord. ~<em>Isaiah 54:17</em>~']
]);

const march = new MonthObj('March', [
    ['Create in me a pure heart, O God, and renew a steadfast spirit within me. ~<em>Psalm 51:10</em>~'],
['You will keep in perfect peace those whose minds are steadfast, because they trust in you. ~<em>Isaiah 26:3</em>~'],
['Therefore, if anyone is in Christ, the new creation has come: The old has gone, the new is here! ~<em>2 Corinthians 5:17</em>~'],
['For where two or three gather in my name, there am I with them. ~<em>Matthew 18:20</em>~'],
['Cast all your anxiety on him because he cares for you. ~<em>1 Peter 5:7</em>~'],
['The Lord is near to all who call on him, to all who call on him in truth. ~<em>Psalm 145:18</em>~'],
['I can do all things through Christ who strengthens me. ~<em>Philippians 4:13</em>~']
['Be still, and know that I am God; I will be exalted among the nations, I will be exalted in the earth. ~<em>Psalm 46:10</em>~'],
['The steadfast love of the Lord never ceases; his mercies never come to an end; they are new every morning; great is your faithfulness. ~<em>Lamentations 3:22-23</em>~'],
['For it is by grace you have been saved, through faith—and this is not from yourselves, it is the gift of God. ~<em>Ephesians 2:8</em>~'],
['And my God will meet all your needs according to the riches of his glory in Christ Jesus. ~<em>Philippians 4:19</em>~'],
['And we know that in all things God works for the good of those who love him, who have been called according to his purpose. ~<em>Romans 8:28</em>~'],
['Therefore do not worry about tomorrow, for tomorrow will worry about itself. Each day has enough trouble of its own. ~<em>Matthew 6:34</em>~'],
['The Lord is good, a refuge in times of trouble. He cares for those who trust in him. ~<em>Nahum 1:7</em>~'],
['Come to me, all you who are weary and burdened, and I will give you rest. ~<em>Matthew 11:28</em>~'],
['For I know the plans I have for you, declares the Lord, plans for welfare and not for evil, to give you a future and a hope. ~<em>Jeremiah 29:11</em>~'],
['For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life. ~<em>John 3:16</em>~'],
['The name of the Lord is a fortified tower; the righteous run to it and are safe. ~<em>Proverbs 18:10</em>~'],
['But the fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness, gentleness and self-control. Against such things there is no law. ~<em>Galatians 5:22-23</em>~'],
['Trust in the Lord with all your heart and lean not on your own understanding; in all your ways submit to him, and he will make your paths straight. ~<em>Proverbs 3:5-6</em>~'],
['Rejoice in the Lord always. I will say it again: Rejoice! ~<em>Philippians 4:4</em>~'],
['For we live by faith, not by sight. ~<em>2 Corinthians 5:7</em>~'],
['Do to others as you would have them do to you. ~<em>Luke 6:31</em>~'],
['In the beginning God created the heaven and the earth. ~<em>Genesis 1:1</em>~'],
['The earth is the Lord’s, and everything in it, the world, and all who live in it. ~<em>Psalm 24:1</em>~'],
['Jesus Christ is the same yesterday and today and forever. ~<em>Hebrews 13:8</em>~'],
['Therefore, if anyone is in Christ, the new creation has come: The old has gone, the new is here! ~<em>2 Corinthians 5:17</em>~'],
['The Lord is my light and my salvation—whom shall I fear? The Lord is the stronghold of my life—of whom shall I be afraid? ~<em>Psalm 27:1</em>~'],
['The Lord bless you and keep you; the Lord make his face shine on you and be gracious to you; the Lord turn his face toward you and give you peace. ~<em>Numbers 6:24-26</em>~'],
['The Lord is near to all who call on him, to all who call on him in truth. ~<em>Psalm 145:18</em>~'],
['But those who hope in the Lord will renew their strength. They will soar on wings like eagles; they will run and not grow weary, they will walk and not be faint. ~<em>Isaiah 40:31</em>~'],
['Therefore, if anyone is in Christ, the new creation has come: The old has gone, the new is here! ~<em>2 Corinthians 5:17</em>~']
]);

const april = new MonthObj('April', [
    ['And whatever you do, whether in word or deed, do it all in the name of the Lord Jesus, giving thanks to God the Father through him. ~<em>Colossians 3:17</em>~'],
['For we are God’s handiwork, created in Christ Jesus to do good works, which God prepared in advance for us to do. ~<em>Ephesians 2:10</em>~'],
['The Lord is gracious and compassionate, slow to anger and rich in love. ~<em>Psalm 145:8</em>~'],
['Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go. ~<em>Joshua 1:9</em>~'],
['Now faith is confidence in what we hope for and assurance about what we do not see. ~<em>Hebrews 11:1</em>~'],
['Blessed are the peacemakers, for they will be called children of God. ~<em>Matthew 5:9</em>~'],
['Finally, be strong in the Lord and in his mighty power. ~<em>Ephesians 6:10</em>~'],
['Above all, love each other deeply, because love covers over a multitude of sins. ~<em>1 Peter 4:8</em>~'],
['Do not let your hearts be troubled. You believe in God; believe also in me. ~<em>John 14:1</em>~'],
['But God demonstrates his own love for us in this: While we were still sinners, Christ died for us. ~<em>Romans 5:8</em>~'],
['The steadfast love of the Lord never ceases; his mercies never come to an end; they are new every morning; great is your faithfulness. ~<em>Lamentations 3:22-23</em>~'],
['Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God. ~<em>Philippians 4:6</em>~'],
['And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus. ~<em>Philippians 4:7</em>~'],
['For I am convinced that neither death nor life, neither angels nor demons, neither the present nor the future, nor any powers, neither height nor depth, nor anything else in all creation, will be able to separate us from the love of God that is in Christ Jesus our Lord. ~<em>Romans 8:38-39</em>~'],
['And my God will meet all your needs according to the riches of his glory in Christ Jesus. ~<em>Philippians 4:19</em>~'],
['And without faith it is impossible to please God, because anyone who comes to him must believe that he exists and that he rewards those who earnestly seek him. ~<em>Hebrews 11:6</em>~'],
['No weapon forged against you will prevail, and you will refute every tongue that accuses you. This is the heritage of the servants of the Lord, and this is their vindication from me, declares the Lord. ~<em>Isaiah 54:17</em>~'],
['For the wages of sin is death, but the gift of God is eternal life in Christ Jesus our Lord. ~<em>Romans 6:23</em>~'],
['Create in me a pure heart, O God, and renew a steadfast spirit within me. ~<em>Psalm 51:10</em>~'],
['For no word from God will ever fail. ~<em>Luke 1:37</em>~'],
['For we are more than conquerors through him who loved us. ~<em>Romans 8:37</em>~'],
['Come to me, all you who are weary and burdened, and I will give you rest. ~<em>Matthew 11:28</em>~'],
['The Lord is near to all who call on him, to all who call on him in truth. ~<em>Psalm 145:18</em>~'],
['Trust in the Lord with all your heart and lean not on your own understanding; in all your ways submit to him, and he will make your paths straight. ~<em>Proverbs 3:5-6</em>~'],
['I can do all things through Christ who strengthens me. ~<em>Philippians 4:13</em>~'],
['Therefore go and make disciples of all nations, baptizing them in the name of the Father and of the Son and of the Holy Spirit. ~<em>Matthew 28:19</em>~'],
['The Lord is my light and my salvation—whom shall I fear? The Lord is the stronghold of my life—of whom shall I be afraid? ~<em>Psalm 27:1</em>~'],
['Above all else, guard your heart, for everything you do flows from it. ~<em>Proverbs 4:23</em>~'],
['For we are God’s handiwork, created in Christ Jesus to do good works, which God prepared in advance for us to do. ~<em>Ephesians 2:10</em>~'],
['The earth is the Lord’s, and everything in it, the world, and all who live in it. ~<em>Psalm 24:1</em>~']
]);

const may = new MonthObj('May', [
    ['Jesus Christ is the same yesterday and today and forever. ~<em>Hebrews 13:8</em>~'],
['And we know that in all things God works for the good of those who love him, who have been called according to his purpose. ~<em>Romans 8:28</em>~'],
['The Lord is my shepherd; I shall not want. ~<em>Psalm 23:1</em>~'],
['The steadfast love of the Lord never ceases; his mercies never come to an end; they are new every morning; great is your faithfulness. ~<em>Lamentations 3:22-23</em>~'],
['Finally, be strong in the Lord and in his mighty power. ~<em>Ephesians 6:10</em>~'],
['For where your treasure is, there your heart will be also. ~<em>Matthew 6:21</em>~'],
['In the beginning God created the heaven and the earth. ~<em>Genesis 1:1</em>~'],
['The Lord bless you and keep you; the Lord make his face shine on you and be gracious to you; the Lord turn his face toward you and give you peace. ~<em>Numbers 6:24-26</em>~'],
['Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God. ~<em>Philippians 4:6</em>~'],
['But God demonstrates his own love for us in this: While we were still sinners, Christ died for us. ~<em>Romans 5:8</em>~'],
['And without faith it is impossible to please God, because anyone who comes to him must believe that he exists and that he rewards those who earnestly seek him. ~<em>Hebrews 11:6</em>~'],
['For I am convinced that neither death nor life, neither angels nor demons, neither the present nor the future, nor any powers, neither height nor depth, nor anything else in all creation, will be able to separate us from the love of God that is in Christ Jesus our Lord. ~<em>Romans 8:38-39</em>~'],
['Above all, love each other deeply, because love covers over a multitude of sins. ~<em>1 Peter 4:8</em>~'],
['For the wages of sin is death, but the gift of God is eternal life in Christ Jesus our Lord. ~<em>Romans 6:23</em>~'],
['And my God will meet all your needs according to the riches of his glory in Christ Jesus. ~<em>Philippians 4:19</em>~'],
['Do to others as you would have them do to you. ~<em>Luke 6:31</em>~'],
['The Lord is gracious and compassionate, slow to anger and rich in love. ~<em>Psalm 145:8</em>~'],
['Be still, and know that I am God; I will be exalted among the nations, I will be exalted in the earth. ~<em>Psalm 46:10</em>~'],
['Finally, be strong in the Lord and in his mighty power. ~<em>Ephesians 6:10</em>~'],
['For no word from God will ever fail. ~<em>Luke 1:37</em>~'],
['Therefore do not worry about tomorrow, for tomorrow will worry about itself. Each day has enough trouble of its own. ~<em>Matthew 6:34</em>~'],
['For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life. ~<em>John 3:16</em>~'],
['Create in me a pure heart, O God, and renew a steadfast spirit within me. ~<em>Psalm 51:10</em>~'],
['The Lord is good, a refuge in times of trouble. He cares for those who trust in him. ~<em>Nahum 1:7</em>~'],
['For we are God’s handiwork, created in Christ Jesus to do good works, which God prepared in advance for us to do. ~<em>Ephesians 2:10</em>~'],
['For where two or three gather in my name, there am I with them. ~<em>Matthew 18:20</em>~'],
['Therefore go and make disciples of all nations, baptizing them in the name of the Father and of the Son and of the Holy Spirit. ~<em>Matthew 28:19</em>~'],
['The Lord is near to all who call on him, to all who call on him in truth. ~<em>Psalm 145:18</em>~'],
['For where your treasure is, there your heart will be also. ~<em>Matthew 6:21</em>~'],
['Jesus Christ is the same yesterday and today and forever. ~<em>Hebrews 13:8</em>~'],
['Above all else, guard your heart, for everything you do flows from it. ~<em>Proverbs 4:23</em>~'],

]);

const june = new MonthObj('June', [
    ['For we live by faith, not by sight. ~<em>2 Corinthians 5:7</em>~'],
['Now faith is confidence in what we hope for and assurance about what we do not see. ~<em>Hebrews 11:1</em>~'],
['And we know that in all things God works for the good of those who love him, who have been called according to his purpose. ~<em>Romans 8:28</em>~'],
['Trust in the Lord with all your heart and lean not on your own understanding; in all your ways submit to him, and he will make your paths straight. ~<em>Proverbs 3:5-6</em>~'],
['I can do all things through Christ who strengthens me. ~<em>Philippians 4:13</em>~'],
['The steadfast love of the Lord never ceases; his mercies never come to an end; they are new every morning; great is your faithfulness. ~<em>Lamentations 3:22-23</em>~'],
['Rejoice in the Lord always. I will say it again: Rejoice! ~<em>Philippians 4:4</em>~'],
['The earth is the Lord’s, and everything in it, the world, and all who live in it. ~<em>Psalm 24:1</em>~'],
['For where two or three gather in my name, there am I with them. ~<em>Matthew 18:20</em>~'],
['The Lord is near to all who call on him, to all who call on him in truth. ~<em>Psalm 145:18</em>~'],
['Do to others as you would have them do to you. ~<em>Luke 6:31</em>~'],
['Create in me a pure heart, O God, and renew a steadfast spirit within me. ~<em>Psalm 51:10</em>~'],
['Therefore go and make disciples of all nations, baptizing them in the name of the Father and of the Son and of the Holy Spirit. ~<em>Matthew 28:19</em>~'],
['Jesus Christ is the same yesterday and today and forever. ~<em>Hebrews 13:8</em>~'],
['Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God. ~<em>Philippians 4:6</em>~'],
['For I know the plans I have for you, declares the Lord, plans for welfare and not for evil, to give you a future and a hope. ~<em>Jeremiah 29:11</em>~'],
['Therefore, if anyone is in Christ, the new creation has come: The old has gone, the new is here! ~<em>2 Corinthians 5:17</em>~'],
['For it is by grace you have been saved, through faith—and this is not from yourselves, it is the gift of God. ~<em>Ephesians 2:8</em>~'],
['Blessed are the peacemakers, for they will be called children of God. ~<em>Matthew 5:9</em>~'],
['But the fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness, gentleness and self-control. Against such things there is no law. ~<em>Galatians 5:22-23</em>~'],
['For where your treasure is, there your heart will be also. ~<em>Matthew 6:21</em>~'],
['For we live by faith, not by sight. ~<em>2 Corinthians 5:7</em>~'],
['Therefore do not worry about tomorrow, for tomorrow will worry about itself. Each day has enough trouble of its own. ~<em>Matthew 6:34</em>~'],
['For we are more than conquerors through him who loved us. ~<em>Romans 8:37</em>~'],
['The Lord is gracious and compassionate, slow to anger and rich in love. ~<em>Psalm 145:8</em>~'],
['Therefore, if anyone is in Christ, the new creation has come: The old has gone, the new is here! ~<em>2 Corinthians 5:17</em>~'],
['The Lord is near to all who call on him, to all who call on him in truth. ~<em>Psalm 145:18</em>~'],
['Finally, be strong in the Lord and in his mighty power. ~<em>Ephesians 6:10</em>~'],
['Do to others as you would have them do to you. ~<em>Luke 6:31</em>~'],
['For where your treasure is, there your heart will be also. ~<em>Matthew 6:21</em>~']

]);

const july = new MonthObj('July', [
    ['The Lord is my light and my salvation—whom shall I fear? The Lord is the stronghold of my life—of whom shall I be afraid? ~<em>Psalm 27:1</em>~'],
['You will keep in perfect peace those whose minds are steadfast, because they trust in you. ~<em>Isaiah 26:3</em>~'],
['For the wages of sin is death, but the gift of God is eternal life in Christ Jesus our Lord. ~<em>Romans 6:23</em>~'],
['I can do all things through Christ who strengthens me. ~<em>Philippians 4:13</em>~'],
['The Lord bless you and keep you; the Lord make his face shine on you and be gracious to you; the Lord turn his face toward you and give you peace. ~<em>Numbers 6:24-26</em>~'],
['In the beginning God created the heaven and the earth. ~<em>Genesis 1:1</em>~'],
['He has shown you, O mortal, what is good. And what does the Lord require of you? To act justly and to love mercy and to walk humbly with your God. ~<em>Micah 6:8</em>~'],
['The steadfast love of the Lord never ceases; his mercies never come to an end; they are new every morning; great is your faithfulness. ~<em>Lamentations 3:22-23</em>~'],
['And we know that in all things God works for the good of those who love him, who have been called according to his purpose. ~<em>Romans 8:28</em>~'],
['For it is by grace you have been saved, through faith—and this is not from yourselves, it is the gift of God. ~<em>Ephesians 2:8</em>~'],
['Let all that you do be done in love. ~<em>1 Corinthians 16:14</em>~'],
['Do not be overcome by evil, but overcome evil with good. ~<em>Romans 12:21</em>~'],
['The name of the Lord is a fortified tower; the righteous run to it and are safe. ~<em>Proverbs 18:10</em>~'],
['For where two or three gather in my name, there am I with them. ~<em>Matthew 18:20</em>~'],
['You will know the truth, and the truth will set you free. ~<em>John 8:32</em>~'],
['The Lord is near to all who call on him, to all who call on him in truth. ~<em>Psalm 145:18</em>~'],
['But the fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness, gentleness and self-control. ~<em>Galatians 5:22-23</em>~'],
['For where your treasure is, there your heart will be also. ~<em>Matthew 6:21</em>~'],
['Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go. ~<em>Joshua 1:9</em>~'],
['The earth is the Lord’s, and everything in it, the world, and all who live in it. ~<em>Psalm 24:1</em>~'],
['For the Lord gives wisdom; from his mouth come knowledge and understanding. ~<em>Proverbs 2:6</em>~'],
['And my God will meet all your needs according to the riches of his glory in Christ Jesus. ~<em>Philippians 4:19</em>~'],
['Be still, and know that I am God; I will be exalted among the nations, I will be exalted in the earth. ~<em>Psalm 46:10</em>~'],
['The Lord is good, a refuge in times of trouble. He cares for those who trust in him. ~<em>Nahum 1:7</em>~'],
['Do to others as you would have them do to you. ~<em>Luke 6:31</em>~'],
['And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus. ~<em>Philippians 4:7</em>~'],
['The Lord is gracious and compassionate, slow to anger and rich in love. ~<em>Psalm 145:8</em>~'],
['And without faith it is impossible to please God, because anyone who comes to him must believe that he exists and that he rewards those who earnestly seek him. ~<em>Hebrews 11:6</em>~'],
['You are the light of the world. A town built on a hill cannot be hidden. ~<em>Matthew 5:14</em>~'],
['For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life. ~<em>John 3:16</em>~'],
['Let everything that has breath praise the Lord. Praise the Lord. ~<em>Psalm 150:6</em>~']
]);

const august = new MonthObj('August', [
    ['The Lord is my shepherd; I lack nothing. ~<em>Psalm 23:1</em>~'],
['He heals the brokenhearted and binds up their wounds. ~<em>Psalm 147:3</em>~'],
['Do not be afraid of them; the Lord your God himself will fight for you. ~<em>Deuteronomy 3:22</em>~'],
['A gentle answer turns away wrath, but a harsh word stirs up anger. ~<em>Proverbs 15:1</em>~'],
['You are my hiding place; you will protect me from trouble and surround me with songs of deliverance. ~<em>Psalm 32:7</em>~'],
['The Lord is my strength and my song; he has become my salvation. ~<em>Exodus 15:2</em>~'],
['Cast all your anxiety on him because he cares for you. ~<em>1 Peter 5:7</em>~'],
['And whatever you do, whether in word or deed, do it all in the name of the Lord Jesus, giving thanks to God the Father through him. ~<em>Colossians 3:17</em>~'],
['The Lord makes firm the steps of the one who delights in him; though he may stumble, he will not fall, for the Lord upholds him with his hand. ~<em>Psalm 37:23-24</em>~'],
['Let your conversation be always full of grace, seasoned with salt, so that you may know how to answer everyone. ~<em>Colossians 4:6</em>~'],
['He gives strength to the weary and increases the power of the weak. ~<em>Isaiah 40:29</em>~'],
['You, Lord, are a shield around me, my glory, the One who lifts my head high. ~<em>Psalm 3:3</em>~'],
['My grace is sufficient for you, for my power is made perfect in weakness. ~<em>2 Corinthians 12:9</em>~'],
['When I am afraid, I put my trust in you. ~<em>Psalm 56:3</em>~'],
['Let us not become weary in doing good, for at the proper time we will reap a harvest if we do not give up. ~<em>Galatians 6:9</em>~'],
['The Lord is a refuge for the oppressed, a stronghold in times of trouble. ~<em>Psalm 9:9</em>~'],
['In your anger do not sin: Do not let the sun go down while you are still angry. ~<em>Ephesians 4:26</em>~'],
['The Lord is good to those whose hope is in him, to the one who seeks him; it is good to wait quietly for the salvation of the Lord. ~<em>Lamentations 3:25-26</em>~'],
['Whoever does not love does not know God, because God is love. ~<em>1 John 4:8</em>~'],
['The righteous cry out, and the Lord hears them; he delivers them from all their troubles. ~<em>Psalm 34:17</em>~'],
['God is our refuge and strength, an ever-present help in trouble. ~<em>Psalm 46:1</em>~'],
['Let us come before him with thanksgiving and extol him with music and song. ~<em>Psalm 95:2</em>~'],
['Rejoice in the Lord always. I will say it again: Rejoice! ~<em>Philippians 4:4</em>~'],
['The fruit of the righteous is a tree of life, and the one who is wise saves lives. ~<em>Proverbs 11:30</em>~'],
['He will cover you with his feathers, and under his wings you will find refuge; his faithfulness will be your shield and rampart. ~<em>Psalm 91:4</em>~'],
['For God did not give us a spirit of timidity, but a spirit of power, of love and of self-discipline. ~<em>2 Timothy 1:7</em>~'],
['Let everything that has breath praise the Lord. ~<em>Psalm 150:6</em>~'],
['Be kind and compassionate to one another, forgiving each other, just as in Christ God forgave you. ~<em>Ephesians 4:32</em>~'],
['I will instruct you and teach you in the way you should go; I will counsel you with my loving eye on you. ~<em>Psalm 32:8</em>~'],
['And whatever you ask in prayer, you will receive, if you have faith. ~<em>Matthew 21:22</em>~'],
['For the Lord watches over the way of the righteous, but the way of the wicked leads to destruction. ~<em>Psalm 1:6</em>~']

]);

const september = new MonthObj('September', [
    ['For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life. ~<em>John 3:16</em>~'],
['Let the peace of Christ rule in your hearts, since as members of one body you were called to peace. And be thankful. ~<em>Colossians 3:15</em>~'],
['Your word is a lamp for my feet, a light on my path. ~<em>Psalm 119:105</em>~'],
['Trust in the Lord with all your heart and lean not on your own understanding; in all your ways submit to him, and he will make your paths straight. ~<em>Proverbs 3:5-6</em>~'],
['He who began a good work in you will carry it on to completion until the day of Christ Jesus. ~<em>Philippians 1:6</em>~'],
['Be strong and take heart, all you who hope in the Lord. ~<em>Psalm 31:24</em>~'],
['Let us not give up meeting together, as some are in the habit of doing, but encourage one another—and all the more as you see the Day approaching. ~<em>Hebrews 10:25</em>~'],
['You are my hiding place; you will protect me from trouble and surround me with songs of deliverance. ~<em>Psalm 32:7</em>~'],
['The Lord is righteous in all his ways and faithful in all he does. ~<em>Psalm 145:17</em>~'],
['No temptation has overtaken you except what is common to mankind. And God is faithful; he will not let you be tempted beyond what you can bear. ~<em>1 Corinthians 10:13</em>~'],
['Commit to the Lord whatever you do, and he will establish your plans. ~<em>Proverbs 16:3</em>~'],
['A friend loves at all times. ~<em>Proverbs 17:17</em>~'],
['Be still before the Lord and wait patiently for him; do not fret when people succeed in their ways, when they carry out their wicked schemes. ~<em>Psalm 37:7</em>~'],
['Give thanks to the Lord, for he is good; his love endures forever. ~<em>Psalm 107:1</em>~'],
['For the Lord gives wisdom; from his mouth come knowledge and understanding. ~<em>Proverbs 2:6</em>~'],
['He will cover you with his feathers, and under his wings you will find refuge; his faithfulness will be your shield and rampart. ~<em>Psalm 91:4</em>~'],
['Let your light shine before others, that they may see your good deeds and glorify your Father in heaven. ~<em>Matthew 5:16</em>~'],
['The Lord bless you and keep you; the Lord make his face shine on you and be gracious to you; the Lord turn his face toward you and give you peace. ~<em>Numbers 6:24-26</em>~'],
['For the Spirit God gave us does not make us timid, but gives us power, love and self-discipline. ~<em>2 Timothy 1:7</em>~'],
['By this everyone will know that you are my disciples, if you love one another. ~<em>John 13:35</em>~'],
['Do not let your hearts be troubled. You believe in God; believe also in me. ~<em>John 14:1</em>~'],
['The Lord is good to those whose hope is in him, to the one who seeks him; it is good to wait quietly for the salvation of the Lord. ~<em>Lamentations 3:25-26</em>~'],
['He makes me lie down in green pastures, he leads me beside quiet waters, he refreshes my soul. ~<em>Psalm 23:2-3</em>~'],
['And God is able to bless you abundantly, so that in all things at all times, having all that you need, you will abound in every good work. ~<em>2 Corinthians 9:8</em>~'],
['The Lord is near to the brokenhearted and saves the crushed in spirit. ~<em>Psalm 34:18</em>~'],
['And whatever you do, whether in word or deed, do it all in the name of the Lord Jesus, giving thanks to God the Father through him. ~<em>Colossians 3:17</em>~'],
['He will not let your foot slip—he who watches over you will not slumber. ~<em>Psalm 121:3</em>~'],
['In all your ways acknowledge him, and he will make your paths straight. ~<em>Proverbs 3:6</em>~'],
['For nothing is impossible with God. ~<em>Luke 1:37</em>~'],
['Blessed is the one who perseveres under trial because, having stood the test, that person will receive the crown of life that the Lord has promised to those who love him. ~<em>James 1:12</em>']

]);

const october = new MonthObj('October', [
    ['The Lord is my rock, my fortress and my deliverer; my God is my rock, in whom I take refuge. ~<em>Psalm 18:2</em>~'],
['For God did not send his Son into the world to condemn the world, but to save the world through him. ~<em>John 3:17</em>~'],
['When you pass through the waters, I will be with you; and when you pass through the rivers, they will not sweep over you. ~<em>Isaiah 43:2</em>~'],
['But the fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness, gentleness and self-control. ~<em>Galatians 5:22-23</em>~'],
['The Lord is my shepherd, I shall not want. ~<em>Psalm 23:1</em>~'],
['Come to me, all you who are weary and burdened, and I will give you rest. ~<em>Matthew 11:28</em>~'],
['The righteous cry out, and the Lord hears them; he delivers them from all their troubles. ~<em>Psalm 34:17</em>~'],
['The Lord is a refuge for the oppressed, a stronghold in times of trouble. ~<em>Psalm 9:9</em>~'],
['Let not your hearts be troubled. Believe in God; believe also in me. ~<em>John 14:1</em>~'],
['Do not let your hearts be troubled. You believe in God; believe also in me. ~<em>John 14:1</em>~'],
['The Lord is good, a refuge in times of trouble. He cares for those who trust in him. ~<em>Nahum 1:7</em>~'],
['For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you, plans to give you a hope and a future. ~<em>Jeremiah 29:11</em>~'],
['And we know that in all things God works for the good of those who love him, who have been called according to his purpose. ~<em>Romans 8:28</em>~'],
['The Lord is my light and my salvation—whom shall I fear? The Lord is the stronghold of my life—of whom shall I be afraid? ~<em>Psalm 27:1</em>~'],
['I can do all things through Christ who strengthens me. ~<em>Philippians 4:13</em>~'],
['The Lord is near to all who call on him, to all who call on him in truth. ~<em>Psalm 145:18</em>~'],
['Let everything that has breath praise the Lord. ~<em>Psalm 150:6</em>~'],
['Your word is a lamp to my feet and a light to my path. ~<em>Psalm 119:105</em>~'],
['The steadfast love of the Lord never ceases; his mercies never come to an end; they are new every morning; great is your faithfulness. ~<em>Lamentations 3:22-23</em>~'],
['So do not fear, for I am with you; do not be dismayed, for I am your God. I will strengthen you and help you; I will uphold you with my righteous right hand. ~<em>Isaiah 41:10</em>~'],
['For the Spirit God gave us does not make us timid, but gives us power, love and self-discipline. ~<em>2 Timothy 1:7</em>~'],
['But the Lord is faithful, and he will strengthen you and protect you from the evil one. ~<em>2 Thessalonians 3:3</em>~'],
['He heals the brokenhearted and binds up their wounds. ~<em>Psalm 147:3</em>~'],
['Let the peace of Christ rule in your hearts, since as members of one body you were called to peace. And be thankful. ~<em>Colossians 3:15</em>~'],
['I sought the Lord, and he answered me; he delivered me from all my fears. ~<em>Psalm 34:4</em>~'],
['If God is for us, who can be against us? ~<em>Romans 8:31</em>~'],
['The Lord will fight for you; you need only to be still. ~<em>Exodus 14:14</em>~'],
['He has shown you, O mortal, what is good. And what does the Lord require of you? To act justly and to love mercy and to walk humbly with your God. ~<em>Micah 6:8</em>~'],
['Be still, and know that I am God; I will be exalted among the nations, I will be exalted in the earth. ~<em>Psalm 46:10</em>~'],
['And whatever you do, whether in word or deed, do it all in the name of the Lord Jesus, giving thanks to God the Father through him. ~<em>Colossians 3:17</em>~'],
['Therefore, as God’s chosen people, holy and dearly loved, clothe yourselves with compassion, kindness, humility, gentleness and patience. ~<em>Colossians 3:12</em>']

]);

const november = new MonthObj('November', [
    ['The Lord is my strength and my defense; he has become my salvation. ~<em>Exodus 15:2</em>~'],
['In all your ways submit to him, and he will make your paths straight. ~<em>Proverbs 3:6</em>~'],
['As for me and my household, we will serve the Lord. ~<em>Joshua 24:15</em>~'],
['For it is by grace you have been saved, through faith—and this is not from yourselves, it is the gift of God. ~<em>Ephesians 2:8</em>~'],
['Be joyful in hope, patient in affliction, faithful in prayer. ~<em>Romans 12:12</em>~'],
['He must increase, but I must decrease. ~<em>John 3:30</em>~'],
['A new command I give you: Love one another. As I have loved you, so you must love one another. ~<em>John 13:34</em>~'],
['For nothing will be impossible with God. ~<em>Luke 1:37</em>~'],
['The Lord will fight for you; you need only to be still. ~<em>Exodus 14:14</em>~'],
['And we know that in all things God works for the good of those who love him, who have been called according to his purpose. ~<em>Romans 8:28</em>~'],
['But the fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness, gentleness and self-control. ~<em>Galatians 5:22-23</em>~'],
['The Lord is compassionate and gracious, slow to anger, abounding in love. ~<em>Psalm 103:8</em>~'],
['Let all that you do be done in love. ~<em>1 Corinthians 16:14</em>~'],
['For God has not given us a spirit of fear, but of power and of love and of a sound mind. ~<em>2 Timothy 1:7</em>~'],
['I can do all things through Christ who strengthens me. ~<em>Philippians 4:13</em>~'],
['The Lord bless you and keep you; the Lord make his face shine on you and be gracious to you; the Lord turn his face toward you and give you peace. ~<em>Numbers 6:24-26</em>~'],
['The Lord is my shepherd, I lack nothing. ~<em>Psalm 23:1</em>~'],
['When you are in distress and all these things have happened to you, then in later days you will return to the Lord your God and obey him. ~<em>Deuteronomy 4:30</em>~'],
['Be kind and compassionate to one another, forgiving each other, just as in Christ God forgave you. ~<em>Ephesians 4:32</em>~'],
['God is our refuge and strength, an ever-present help in trouble. ~<em>Psalm 46:1</em>~'],
['For where two or three gather in my name, there am I with them. ~<em>Matthew 18:20</em>~'],
['He who dwells in the secret place of the Most High shall abide under the shadow of the Almighty. ~<em>Psalm 91:1</em>~'],
['The Lord is good to those who wait for him, to the soul who seeks him. ~<em>Lamentations 3:25</em>~'],
['You will keep in perfect peace those whose minds are steadfast, because they trust in you. ~<em>Isaiah 26:3</em>~'],
['And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus. ~<em>Philippians 4:7</em>~'],
['But those who hope in the Lord will renew their strength. They will soar on wings like eagles; they will run and not grow weary, they will walk and not be faint. ~<em>Isaiah 40:31</em>~'],
['For the Lord is righteous, he loves justice; the upright will see his face. ~<em>Psalm 11:7</em>~'],
['The name of the Lord is a fortified tower; the righteous run to it and are safe. ~<em>Proverbs 18:10</em>~'],
['And let us consider how we may spur one another on toward love and good deeds. ~<em>Hebrews 10:24</em>~'],
['Therefore, if anyone is in Christ, the new creation has come: The old has gone, the new is here! ~<em>2 Corinthians 5:17</em>']
]);

const december = new MonthObj('December', [
    ['You are the light of the world. A town built on a hill cannot be hidden. ~<em>Matthew 5:14</em>~'],
['Do not let your hearts be troubled. You believe in God; believe also in me. ~<em>John 14:1</em>~'],
['For where your treasure is, there your heart will be also. ~<em>Matthew 6:21</em>~'],
['The Lord is my portion; therefore I will wait for him. ~<em>Lamentations 3:24</em>~'],
['Peace I leave with you; my peace I give you. I do not give to you as the world gives. Do not let your hearts be troubled and do not be afraid. ~<em>John 14:27</em>~'],
['The Lord’s unfailing love surrounds the one who trusts in him. ~<em>Psalm 32:10</em>~'],
['I will praise you, Lord, with all my heart; I will tell of all your wonderful deeds. ~<em>Psalm 9:1</em>~'],
['For we live by faith, not by sight. ~<em>2 Corinthians 5:7</em>~'],
['The Lord is my strength and my shield; my heart trusts in him, and he helps me. ~<em>Psalm 28:7</em>~'],
['And whatever you do, whether in word or deed, do it all in the name of the Lord Jesus, giving thanks to God the Father through him. ~<em>Colossians 3:17</em>~'],
['The righteous person may have many troubles, but the Lord delivers him from them all. ~<em>Psalm 34:19</em>~'],
['For God is not a God of disorder but of peace. ~<em>1 Corinthians 14:33</em>~'],
['I will never leave you nor forsake you. ~<em>Hebrews 13:5</em>~'],
['The Lord is good to those who wait for him, to the soul who seeks him. ~<em>Lamentations 3:25</em>~'],
['Let everything that has breath praise the Lord. ~<em>Psalm 150:6</em>~'],
['But the Lord is faithful, and he will strengthen you and protect you from the evil one. ~<em>2 Thessalonians 3:3</em>~'],
['In the same way, let your light shine before others, that they may see your good deeds and glorify your Father in heaven. ~<em>Matthew 5:16</em>~'],
['The Lord bless you and keep you; the Lord make his face shine on you and be gracious to you; the Lord turn his face toward you and give you peace. ~<em>Numbers 6:24-26</em>~'],
['For God has not given us a spirit of fear, but of power and of love and of a sound mind. ~<em>2 Timothy 1:7</em>~'],
['He has shown you, O mortal, what is good. And what does the Lord require of you? To act justly and to love mercy and to walk humbly with your God. ~<em>Micah 6:8</em>~'],
['And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus. ~<em>Philippians 4:7</em>~'],
['The Lord is near to the brokenhearted and saves the crushed in spirit. ~<em>Psalm 34:18</em>~'],
['Give thanks to the Lord, for he is good; his love endures forever. ~<em>Psalm 107:1</em>~'],
['For the Lord gives wisdom; from his mouth come knowledge and understanding. ~<em>Proverbs 2:6</em>~'],
['The Lord is righteous in all his ways and faithful in all he does. ~<em>Psalm 145:17</em>~'],
['I sought the Lord, and he answered me; he delivered me from all my fears. ~<em>Psalm 34:4</em>~'],
['Let us hold unswervingly to the hope we profess, for he who promised is faithful. ~<em>Hebrews 10:23</em>~'],
['Therefore, if anyone is in Christ, the new creation has come: The old has gone, the new is here! ~<em>2 Corinthians 5:17</em>~'],
['But those who hope in the Lord will renew their strength. They will soar on wings like eagles; they will run and not grow weary, they will walk and not be faint. ~<em>Isaiah 40:31</em>~'],
['For no word from God will ever fail. ~<em>Luke 1:37</em>~'],
['You will keep in perfect peace those whose minds are steadfast, because they trust in you. ~<em>Isaiah 26:3</em>~']
]);

//exports
export { january, february, march, april, may, june, july, august, september, october, november, december };
